@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "org.example.view.EditorDialog",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_123453861 { 
   	label=model
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Monstr823774235[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Monstr</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   additional_info: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   first_mention: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   full_info: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   habitat: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   immunities: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   physical_characteristics: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   potion: Potion [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Potion823774235[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Potion</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ingredients: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   preparation_time: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   strength: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_134302551 { 
   	label=view
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   EditorDialog2051374221[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EditorDialog</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   current: JDialog [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldAdditionalInfo: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldDescription: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldFirstMention: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldFullInfo: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldHabitat: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldImmunities: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldIngredients: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldName: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldPhysicalCharacteristics: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldPreparationTime: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   fieldStrength: JTextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   monstr: Monstr [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   parent: JFrame [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addField(panel: JPanel, label: String, value: String, setter: Consumer&lt;String&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" ># initEditorDialog()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
EditorDialog2051374221 -> Monstr823774235[label="monstr
[0..1]"];
Monstr823774235 -> Potion823774235[label="potion
[0..1]"];
    
}
@enduml